# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SMainWindow(object):
    def setupUi(self, SMainWindow):
        SMainWindow.setObjectName("SMainWindow")
        SMainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(SMainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.centralwidget.setFont(font)
        self.centralwidget.setToolTip("")
        self.centralwidget.setObjectName("centralwidget")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("#frame_2{\n"
"    background-color: rgb(186, 143, 255);\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(0,0,0,0);\n"
"    color: rgb(255,255,255);\n"
"    border: none;\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top: 5px;\n"
"    padding-left:5px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_S_shopping = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_S_shopping.setObjectName("pushButton_S_shopping")
        self.verticalLayout.addWidget(self.pushButton_S_shopping)
        self.pushButton_S_order = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_S_order.setObjectName("pushButton_S_order")
        self.verticalLayout.addWidget(self.pushButton_S_order)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_S_update_pw = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_S_update_pw.setObjectName("pushButton_S_update_pw")
        self.verticalLayout.addWidget(self.pushButton_S_update_pw)
        self.pushButton_login_out = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_login_out.setObjectName("pushButton_login_out")
        self.verticalLayout.addWidget(self.pushButton_login_out)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_3)
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_4 = QtWidgets.QFrame(self.page)
        self.frame_4.setMinimumSize(QtCore.QSize(600, 500))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("QLineEdit{\n"
"    bakground-color: rgb(255,255,255,0);\n"
"    border: none;\n"
"    border-bottom: 1px solid black;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(0,0,0);\n"
"    color: rgb(255,255,255);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top: 5px;\n"
"    padding-left:5px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_S_M_studentID = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_S_M_studentID.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_S_M_studentID.setText("")
        self.lineEdit_S_M_studentID.setObjectName("lineEdit_S_M_studentID")
        self.horizontalLayout_4.addWidget(self.lineEdit_S_M_studentID)
        self.lineEdit_S_M_bookID = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_S_M_bookID.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_S_M_bookID.setText("")
        self.lineEdit_S_M_bookID.setObjectName("lineEdit_S_M_bookID")
        self.horizontalLayout_4.addWidget(self.lineEdit_S_M_bookID)
        self.pushButton_S_M_order_sure = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_S_M_order_sure.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_S_M_order_sure.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_S_M_order_sure.setObjectName("pushButton_S_M_order_sure")
        self.horizontalLayout_4.addWidget(self.pushButton_S_M_order_sure)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableView_S_M_bookList = QtWidgets.QTableView(self.frame_6)
        self.tableView_S_M_bookList.setObjectName("tableView_S_M_bookList")
        self.horizontalLayout_3.addWidget(self.tableView_S_M_bookList)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.horizontalLayout_14.addWidget(self.frame_4)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_7 = QtWidgets.QFrame(self.page_2)
        self.frame_7.setMinimumSize(QtCore.QSize(600, 500))
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setStyleSheet("QLineEdit{\n"
"    bakground-color: rgb(255,255,255,0);\n"
"    border: none;\n"
"    border-bottom: 1px solid black;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(0,0,0);\n"
"    color: rgb(255,255,255);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top: 5px;\n"
"    padding-left:5px;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lineEdit_S_M_order_update = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_S_M_order_update.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_S_M_order_update.setText("")
        self.lineEdit_S_M_order_update.setObjectName("lineEdit_S_M_order_update")
        self.horizontalLayout_12.addWidget(self.lineEdit_S_M_order_update)
        self.pushButton_S_M_order_sure_update = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_S_M_order_sure_update.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_S_M_order_sure_update.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_S_M_order_sure_update.setObjectName("pushButton_S_M_order_sure_update")
        self.horizontalLayout_12.addWidget(self.pushButton_S_M_order_sure_update)
        self.verticalLayout_7.addWidget(self.frame_9)
        self.frame_16 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.frame_16.sizePolicy().hasHeightForWidth())
        self.frame_16.setSizePolicy(sizePolicy)
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.tableView_2 = QtWidgets.QTableView(self.frame_16)
        self.tableView_2.setObjectName("tableView_2")
        self.horizontalLayout_13.addWidget(self.tableView_2)
        self.verticalLayout_7.addWidget(self.frame_16)
        self.horizontalLayout_5.addWidget(self.frame_7)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.frame_8 = QtWidgets.QFrame(self.page_3)
        self.frame_8.setGeometry(QtCore.QRect(100, 80, 431, 391))
        self.frame_8.setStyleSheet("QLineEdit{\n"
"    bakground-color: rgb(255,255,255,0);\n"
"    border: none;\n"
"    border-bottom: 1px solid black;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(0,0,0);\n"
"    color: rgb(255,255,255);\n"
"    border-radius: 7px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top: 5px;\n"
"    padding-left:5px;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_S_M_password = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_S_M_password.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_S_M_password.setText("")
        self.lineEdit_S_M_password.setObjectName("lineEdit_S_M_password")
        self.verticalLayout_3.addWidget(self.lineEdit_S_M_password)
        self.lineEdit_S_M_new_password = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_S_M_new_password.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_S_M_new_password.setText("")
        self.lineEdit_S_M_new_password.setObjectName("lineEdit_S_M_new_password")
        self.verticalLayout_3.addWidget(self.lineEdit_S_M_new_password)
        self.lineEdit_S_M_new_password_sure = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_S_M_new_password_sure.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_S_M_new_password_sure.setText("")
        self.lineEdit_S_M_new_password_sure.setObjectName("lineEdit_S_M_new_password_sure")
        self.verticalLayout_3.addWidget(self.lineEdit_S_M_new_password_sure)
        self.pushButton_S_M_sure = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_S_M_sure.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_S_M_sure.setObjectName("pushButton_S_M_sure")
        self.verticalLayout_3.addWidget(self.pushButton_S_M_sure)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_8)
        self.stackedWidget_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget_2.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_4 = QtWidgets.QLabel(self.page_5)
        self.label_4.setGeometry(QtCore.QRect(160, 0, 81, 39))
        self.label_4.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.stackedWidget_2.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_5 = QtWidgets.QLabel(self.page_6)
        self.label_5.setGeometry(QtCore.QRect(130, 10, 161, 39))
        self.label_5.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.stackedWidget_2.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.label_6 = QtWidgets.QLabel(self.page_7)
        self.label_6.setGeometry(QtCore.QRect(180, 0, 81, 39))
        self.label_6.setStyleSheet("color: rgb(255, 182, 38);")
        self.label_6.setObjectName("label_6")
        self.stackedWidget_2.addWidget(self.page_7)
        self.verticalLayout_3.addWidget(self.stackedWidget_2)
        self.stackedWidget.addWidget(self.page_3)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.hboxlayout.addWidget(self.frame)
        SMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SMainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SMainWindow)

    def retranslateUi(self, SMainWindow):
        _translate = QtCore.QCoreApplication.translate
        SMainWindow.setWindowTitle(_translate("SMainWindow", "MainWindow"))
        self.pushButton_S_shopping.setText(_translate("SMainWindow", "订购教材"))
        self.pushButton_S_order.setText(_translate("SMainWindow", "我的订购"))
        self.pushButton_S_update_pw.setText(_translate("SMainWindow", "修改密码"))
        self.pushButton_login_out.setText(_translate("SMainWindow", "退出登录"))
        self.lineEdit_S_M_studentID.setPlaceholderText(_translate("SMainWindow", "学号："))
        self.lineEdit_S_M_bookID.setPlaceholderText(_translate("SMainWindow", "书号：下方查看对应书籍的书号"))
        self.pushButton_S_M_order_sure.setText(_translate("SMainWindow", "确认"))
        self.lineEdit_S_M_order_update.setPlaceholderText(_translate("SMainWindow", "订单号：下方查看对应订单号"))
        self.pushButton_S_M_order_sure_update.setText(_translate("SMainWindow", "确认删除订单"))
        self.lineEdit_S_M_password.setPlaceholderText(_translate("SMainWindow", "原密码："))
        self.lineEdit_S_M_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_S_M_new_password.setPlaceholderText(_translate("SMainWindow", "新密码："))
        self.lineEdit_S_M_new_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_S_M_new_password_sure.setPlaceholderText(_translate("SMainWindow", "确认新密码："))
        self.lineEdit_S_M_new_password_sure.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pushButton_S_M_sure.setText(_translate("SMainWindow", "确认"))
        self.label_4.setText(_translate("SMainWindow", "密码不能为空"))
        self.label_5.setText(_translate("SMainWindow", "原密码错误或新密码不一致"))
        self.label_6.setText(_translate("SMainWindow", "修改成功"))
